######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Las Montañas Inn | Wellness Travel Destination in Rural Majestic Colombia"
theme = "restaurant-hugo"
summaryLength = "7"
paginate = 8
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$","\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
googleAnalytics = "UA-81176691-4"
staticDir = ["assets"]
#defaultContentLanguage = "en"
############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "/css/slick.css"
  [[params.plugins.css]]
  URL = "/css/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "/css/animate.min.css"
  [[params.plugins.css]]
  URL = "/css/venobox.css"
  [[params.plugins.css]]
  URL = "/css/main.css"
  [[params.plugins.css]]
  URL = "/css/responsive.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/slick.min.js"
  [[params.plugins.js]]
  URL = "js/wow.min.js"
  [[params.plugins.js]]
  URL = "js/venobox.min.js"
  [[params.plugins.js]]
  URL = "js/main.js"
  
############################## navigation ###############################
[menu]
	
	[[menu.main]]
  name = ""
  URL = "hero-area"
  weight = 1

  [[menu.main]]
  name = "Las Montañas"
  URL = "about-us"
  weight = 2

  [[menu.main]]
  name = "Experiences"
  URL = "blog"
  weight = 3

  [[menu.main]]
  name = "Packages"
  URL = "price"
  weight = 4

  [[menu.main]]
  name = "Book Now"
  URL = "contact-us"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo-2023.png"
copyright = "Copyright 2019 - Las Montañas Inn"
description = "Hilltop Inn along the south of Medellin. Our Santa Barbara bed and breakfast offers luxury rooms, stunning gardens, country views & amazing meals on a 3 acre paisa finca along el eje cafetero. Escape today!"
author = "Las Montañas Inn"
privacy = "privacy-policy"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "GET IN <span>TOUCH</span> "
image = "images/QR Whatsapp LM.png"
blogTitle = "LAS <span>MONTAÑAS</span>"
galleryTitle = "OUR <span>VIEWS</span>"
socialTitle = "Follow <span>US</span>"
path = "images/slider"
apiURL = "https://wa.me/message/VIDY2WHBHXUXJ1?src=qr"

############################ footer contact item
[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content =  "+57 (317) 211 4410"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "[Vereda Atanasio, Santa Barbara, Colombia](https://www.google.com/maps/place/Hoster%C3%ADa+Las+Monta%C3%B1as/@5.8674093,-75.5625925,15z/data=!4m6!3m5!1s0x8e46f32c43089c17:0x95844c8761d44042!8m2!3d5.8584234!4d-75.5566042!16s%2Fg%2F11g1ly8gjq?entry=ttu)"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "Las Montañas Inn - escapetolasmontanas@gmail.com"

######################### footer gallery

[[params.footer.gallery]]
image = "images/slider/r/f1.jpg"

[[params.footer.gallery]]
image = "images/slider/r/f2.jpg"

[[params.footer.gallery]]
image = "images/slider/r/f3.jpg"

[[params.footer.gallery]]
image = "images/slider/r/f4.jpg"

[[params.footer.gallery]]
image = "images/slider/r/f5.jpg"

[[params.footer.gallery]]
image = "images/slider/r/f7.jpg"

######################## Social Icon
[[params.footer.socialLink]]
icon = "facebook"
link = "//facebook.com/escapetolasmontanas"

[[params.footer.socialLink]]
icon = "twitter"
link = "//twitter.com/escapetolasmontanas"

[[params.footer.socialLink]]
icon = "tiktok"
link = "//tiktok.com/escapetolasmontanas"
[[params.footer.socialLink]]
icon = "youtube"
link = "//youtube.com/@LasMontanasInn"
#
#[[params.footer.socialLink]]
#icon = "airbnb"
#link = "//airbnb.com/rooms/26280452"

[[params.footer.socialLink]]
icon = "instagram"
link = "//instagram.com/escapetolasmontanas"
